# Generated by Django 4.2.6 on 2023-10-09 23:52

from django.db import migrations, models
import django.db.models.deletion
import oauthtesting.models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0002_alter_account_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='Username',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='account',
            name='picture',
            field=models.ImageField(upload_to=oauthtesting.models.account_url),
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauthtesting.username'),
        ),
    ]
