# Generated by Django 4.2.6 on 2023-10-11 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0003_username_alter_account_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Username',
        ),
    ]
