# Generated by Django 4.2.6 on 2023-10-20 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0004_alter_account_username_delete_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.CreateModel(
            name='POI',
            fields=[
                ('pid', models.IntegerField(primary_key=True, serialize=False)),
                ('time', models.DateTimeField()),
                ('points', models.IntegerField(default=1)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8)),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='id',
        ),
        migrations.AlterField(
            model_name='account',
            name='username',
            field=models.CharField(max_length=64, primary_key=True, serialize=False, unique=True),
        ),
        migrations.CreateModel(
            name='Captured',
            fields=[
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='oauthtesting.poi')),
                ('time', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='DrawingMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oauthtesting.message')),
                ('data', models.FileField(upload_to='drawing')),
            ],
            bases=('oauthtesting.message',),
        ),
        migrations.CreateModel(
            name='TextMessage',
            fields=[
                ('message_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='oauthtesting.message')),
                ('text', models.CharField(max_length=200)),
            ],
            bases=('oauthtesting.message',),
        ),
        migrations.AddField(
            model_name='message',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauthtesting.account'),
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauthtesting.account')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauthtesting.message')),
            ],
        ),
        migrations.CreateModel(
            name='Friends',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user1', to='oauthtesting.account')),
                ('user2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user2', to='oauthtesting.account')),
            ],
        ),
        migrations.AddConstraint(
            model_name='message',
            constraint=models.UniqueConstraint(fields=('username', 'time'), name='message_id'),
        ),
        migrations.AddConstraint(
            model_name='like',
            constraint=models.UniqueConstraint(fields=('poster', 'liker'), name='like_id'),
        ),
        migrations.AddConstraint(
            model_name='friends',
            constraint=models.UniqueConstraint(fields=('user1', 'user2'), name='friend_key'),
        ),
        migrations.AddField(
            model_name='captured',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauthtesting.account'),
        ),
    ]
