# Generated by Django 4.2.6 on 2023-10-22 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0005_message_poi_remove_account_id_alter_account_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='name',
            field=models.CharField(default='A Point of Interest', max_length=100),
        ),
    ]
