# Generated by Django 4.2.6 on 2023-10-30 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0006_poi_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='points',
            field=models.IntegerField(default=200),
        ),
    ]
