# Generated by Django 4.2.6 on 2023-10-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0007_alter_poi_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='img',
            field=models.ImageField(default='images/rotunda.jpeg', upload_to='images/'),
        ),
    ]
