# Generated by Django 4.2.6 on 2023-11-04 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0008_poi_img'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='message',
            name='message_id',
        ),
        migrations.AddField(
            model_name='message',
            name='message',
            field=models.CharField(default='Default message', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='message',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='message',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='message',
            name='time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
