# Generated by Django 4.2.6 on 2023-11-05 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("oauthtesting", "0009_remove_message_message_id_message_message_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="approved",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="message",
            name="latitude",
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name="message",
            name="longitude",
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
