# Generated by Django 4.2.6 on 2023-11-05 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0009_remove_message_message_id_message_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='message',
        ),
        migrations.RemoveField(
            model_name='textmessage',
            name='text',
        ),
        migrations.AddField(
            model_name='textmessage',
            name='message',
            field=models.CharField(default='Default message', max_length=200),
        ),
        migrations.AlterField(
            model_name='message',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
        migrations.AlterField(
            model_name='message',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=8),
        ),
    ]
