# Generated by Django 4.2.6 on 2023-11-05 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("oauthtesting", "0010_message_approved_alter_message_latitude_and_more"),
        (
            "oauthtesting",
            "0010_remove_message_message_remove_textmessage_text_and_more",
        ),
    ]

    operations = []
