# Generated by Django 4.2.6 on 2023-11-05 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0012_alter_message_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='time',
        ),
    ]
