# Generated by Django 4.2.6 on 2023-11-05 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0012_alter_message_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cost', models.IntegerField()),
                ('category', models.CharField(choices=[('background', 'Background Color'), ('border', 'Profile Border')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_purchased', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauthtesting.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauthtesting.account')),
            ],
        ),
        migrations.CreateModel(
            name='Account_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('background', models.ForeignKey(blank=True, limit_choices_to={'category': 'background'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_background', to='oauthtesting.item')),
                ('border', models.ForeignKey(blank=True, limit_choices_to={'category': 'border'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selected_border', to='oauthtesting.item')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauthtesting.account')),
            ],
        ),
    ]
