# Generated by Django 4.2.6 on 2023-11-07 02:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0013_item_purchase_account_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='css',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('background', 'Background'), ('border', 'Border')], max_length=50),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauthtesting.item'),
        ),
        migrations.DeleteModel(
            name='Account_Profile',
        ),
        migrations.AddField(
            model_name='accountitem',
            name='item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='oauthtesting.item'),
        ),
        migrations.AddField(
            model_name='accountitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='oauthtesting.account'),
        ),
        migrations.AlterUniqueTogether(
            name='accountitem',
            unique_together={('user', 'item_category')},
        ),
    ]
