# Generated by Django 4.2.6 on 2023-11-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0014_accountitem_item_css_alter_item_category_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AccountItem',
            new_name='Account_Profile',
        ),
    ]
