# Generated by Django 4.2.6 on 2023-11-07 05:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0015_rename_accountitem_account_profile'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='account_profile',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='account_profile',
            name='background',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'background'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='background_profiles', to='oauthtesting.item'),
        ),
        migrations.AddField(
            model_name='account_profile',
            name='border',
            field=models.ForeignKey(blank=True, limit_choices_to={'category': 'border'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='border_profiles', to='oauthtesting.item'),
        ),
        migrations.AlterField(
            model_name='account_profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='oauthtesting.account'),
        ),
        migrations.RemoveField(
            model_name='account_profile',
            name='item',
        ),
        migrations.RemoveField(
            model_name='account_profile',
            name='item_category',
        ),
    ]
