# Generated by Django 4.2.6 on 2023-11-08 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0013_remove_like_time'),
        ('oauthtesting', '0016_alter_account_profile_unique_together_and_more'),
    ]

    operations = [
    ]
