# Generated by Django 4.2.6 on 2023-11-12 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0018_alter_account_bio'),
        ('oauthtesting', '0018_alter_account_picture'),
    ]

    operations = [
    ]
