# Generated by Django 4.2.6 on 2023-11-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0019_merge_20231112_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='poi',
            name='lastupdated',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='poi',
            name='owner',
            field=models.CharField(blank=True, default=None, max_length=64, null=True),
        ),
    ]
