# Generated by Django 4.2.6 on 2023-11-12 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0020_poi_lastupdated_poi_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='pid',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
