# Generated by Django 4.2.6 on 2023-11-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0021_alter_poi_pid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poi',
            name='points',
            field=models.IntegerField(default=1),
        ),
    ]
