# Generated by Django 4.2.6 on 2023-11-12 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0022_alter_poi_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('background', 'Background'), ('border', 'Border'), ('renewable', 'Renewable')], max_length=50),
        ),
    ]
