# Generated by Django 4.2.6 on 2023-12-03 04:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauthtesting', '0025_message_rejected_message_rejection_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='rejection_message',
            new_name='rejection_reason',
        ),
    ]
